### ISSUE TITLE
daddy issues from MathiasH#6640

### ISSUE THREAD

**Issue by HalsMaulMajo** [HalsMaulMajo/majotools#1]
Hey, i have here on discord a guy that has many daddy issues.
Add him as firend and try to fix it please

**Comment by HalsMaulMajo** [comment]
here: https://discord.gg/AQ2pES4Q

**Comment by era6-6-6** [comment]
Hmm it's really hard to fix this issue :( we need more info about this issue :(

**Comment by HalsMaulMajo** [comment]
yeah, i understand....
let me explain.... 
he think he is my dad and he make strange sounds... ("with his mouth!")

**Comment by era6-6-6** [comment]
And he is your son if I understand right ?

**Comment by HalsMaulMajo** [comment]
and he think someone want to kill him.... thats strange

**Comment by HalsMaulMajo** [comment]
nono! no really, he think that im his dad, but thats not the truth

**Comment by era6-6-6** [comment]
Well if this is the case I have solution I think. I found this website it's perfect solution for his problem! https://www.guterhirte-ludwigshafen.de/ try it and tell us if this solution works !

**Comment by HalsMaulMajo** [comment]
yes, i think it works! i send him there later!!!
